name: Clf Model Workflow
on: 
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.10"

      # Install databricks CLI as per https://docs.databricks.com/dev-tools/cli/databricks-cli.html
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Set PYTHONPATH and Run Tests
        run: |
          export PYTHONPATH=notebook  # Set PYTHONPATH to the src directory
          pytest tests  # Run tests located in the tests directory

      # List the databricks repos within the workspace whose credentials are stored in the Github Environment "my-environment"
      # - name: List databricks repos
      #   env:
      #     # Note the host is an "environment variable" in the Github Environment while the token is a "secret" in the Github Environment
      #     DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      #   run: |
      #     databricks repos list
