name: Clf Model Workflow
on: 
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run a simple test
        run: |
          echo "Hello World"
          echo "This is a test job running on Github Actions."
