name: Wine Quality Prediction Model Workflow
on: 
  push:
    branches:
      - dev
      - main

jobs:
  dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    env: 
      MLFLOW_TRACKING_URI: "databricks"
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }} #Workspace level host. 
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      
      - name: Verify Databricks CLI Installation
        run: |
          databricks --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run CLI Tool using Databricks credentials
        run: |
          export PYTHONPATH=cli_tool
          python cli_tool/cli.py deploy

      - name: Set PYTHONPATH and Run Tests
        run: |
          export PYTHONPATH=notebooks  # Set PYTHONPATH to the src directory
          pytests tests  # Run tests located in the tests directory
      # - name: Run CLI Tool using Databricks credentials
      #   env: 
      #     MLFLOW_TRACKING_URI: "databricks"
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }} #Workspace level host 
      #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
      #   run: |
      #     export PYTHONPATH=cli_tool
      #     python cli_tool/cli.py deploy
        
      # - name: Set PYTHONPATH and Run Tests
      #   # env: 
      #   #   MLFLOW_TRACKING_URI: "databricks"
      #   #   DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }} #Workspace level host 
      #   #   DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      #   run: |
      #     export PYTHONPATH=notebooks  # Set PYTHONPATH to the src directory
      #     python notebooks/train_model_py.py  # Run tests located in the tests directory
  # deploy-dev:
  #   runs-on: ubuntu-latest
  #   env: 
  #     MLFLOW_TRACKING_URI: "databricks"
  #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }} #Workspace level host. 
  #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
  #   needs: build
  #   if: github.ref == 'refs/heads/dev' # This will only run on dev branch

  #   steps:

      
  #     - name: Run CLI Tool using Databricks credentials
  #       run: |
  #         export PYTHONPATH=cli_tool
  #         python cli_tool/cli.py deploy

  #     - name: Set PYTHONPATH and Run Tests
  #       run: |
  #         export PYTHONPATH=notebooks  # Set PYTHONPATH to the src directory
  #         pytests tests  # Run tests located in the tests directory
  
  deploy-main:
    runs-on: ubuntu-latest
    env: 
      MLFLOW_TRACKING_URI: "databricks"
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }} #Workspace level host. 
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
    if: github.ref == 'refs/heads/main' # This will only run on main branch

    steps:
      - name: Run CLI Tool using Databricks credentials
        run: |
          export PYTHONPATH=cli_tool
          python cli_tool/cli.py deploy

      - name: Set PYTHONPATH and Run Tests
        run: |
          export PYTHONPATH=notebooks  # Set PYTHONPATH to the src directory
          pytest tests  # Run tests located in the tests directory



      