name: CLF Model Workflow
on: 
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Set PYTHONPATH and Run Tests
        run: |
          export PYTHONPATH=notebooks  # Set PYTHONPATH to the src directory
          python tests/test_training.py  # Run tests located in the tests directory
          python tests/test_inference.py  # Run tests located in the tests directory
     
      - name: Run CLI Tool using Databricks credentials
        env: 
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }} #Workspace level host 
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
        run: |
          export PYTHONPATH=cli_tool
          python cli_tool/cli.py

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev' # This will only run on dev branch

    steps:
      - name: Set PYTHONPATH and Run Tests
        run: |
          export PYTHONPATH=notebooks  # Set PYTHONPATH to the src directory
          python tests/test_training.py  # Run tests located in the tests directory
          python tests/test_inference.py  # Run tests located in the tests directory
      
      # - name: Run CLI Tool using Databricks credentials
      #   env: 
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }} #Workspace level host 
      #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
      #   run: |
      #     export PYTHONPATH=cli_tool
      #     python cli_tool/cli.py

  deploy-main:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # This will only run on main branch

    steps:
      - name: Set PYTHONPATH and Run Tests
        run: |
          export PYTHONPATH=notebooks  # Set PYTHONPATH to the src directory
          pytest tests  # Run tests located in the tests directory

      - name: Run CLI Tool using Databricks credentials
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }} #Workspace level host 
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
        run: |
          python cli_tool/cli.py


      